name: tostore
description: A advanced storage engine that supports relational and NoSQL database,data smart cache, multi-space architecture,file/local storage, SQL & key-value persistent store.
version: 3.0.5
homepage: https://github.com/tocreator/tostore
repository: https://github.com/tocreator/tostore
documentation: https://github.com/tocreator/tostore/wiki

topics:
  - database
  - storage
  - sql
  - nosql
  - distributed

environment:
  sdk: ^3.5.4

dependencies:
  path: ^1.9.1
  archive: ^4.0.7
  web: ^1.1.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.28.0
